import numpy as np
import matplotlib.pyplot as plt
t=np.arange(0,10,0.1)
x1=np.sin(2*np.pi*t)
x2=np.cos(2*np.pi*t)
x3=np.sin(2*np.pi*t)+np.cos(2*np.pi*t)
x4=np.cos(2*np.pi*t)-np.sin(2*np.pi*t)
plt.subplot(2,2,1)
plt.title("sin wave")
plt.xlabel("time")
plt.ylabel("amplitude")
plt.plot(t,x1,'b')
plt.subplot(2,2,2)
plt.title("cos wave")
plt.xlabel("time")
plt.ylabel("amplitude")
plt.plot(t,x2,'r')
plt.subplot(2,2,3)
plt.plot(t,x3,'g')
plt.title("addition of cos and sin")
plt.xlabel("time")
plt.ylabel("amplitude")
plt.subplot(2,2,4)
plt.plot(t,x4,'g')
plt.title("subtraction of cos and sin")
plt.xlabel("time")
plt.ylabel("amplitude")
plt.show()